### ISSUE TITLE
Issue with cacert.pem

### ISSUE THREAD

**Issue by mlordi** [IntuitDeveloper/OAuth2_PHP#6]
I have tried all different ways of generating the ssl cert to work with this script. I have downloaded the Mozilla one. I have used openssl to regenerate a pem from cer file that I got from ngrok but I keep getting this error.

Fatal error: Uncaught Exception: error setting certificate verify locations: CAfile: ./Certificate/cacert-2017-06-07.pem CApath: none in C:\wamp64\www\plugins\quickbooks\Client.php:186 Stack trace: #0 C:\wamp64\www\plugins\quickbooks\Client.php(86): Client->executeRequest('https://oauth.p...', Array, Array, 'POST') #1 C:\wamp64\www\plugins\quickbooks\OAuth2PHPExample.php(45): Client->getAccessToken('https://oauth.p...', 'L01150395379466...', 'https://aefb615...', 'authorization_c...') #2 {main} thrown in C:\wamp64\www\plugins\quickbooks\Client.php on line 186

**Comment by jfkhome** [comment]
Hi

Not sure if you have the same issue but a number of us have had problems with the example app script finding our certs. Not the cert itself. I ended up putting mine in the web directory and changing the path in the example to point to it like so
'C:/xampp/htdocs/myapp/web/certificates/cacert.pem'

**Comment by mlordi** [comment]
Thanks @jfkhome for the help. I ended up changing client.php files line 164 to:
    curl_setopt($ch,` CURLOPT_CAINFO, dirname(__FILE__)."\Certificate\cacert.pem");

This worked and now authorized without any issues.

**Comment by jfkhome** [comment]
Glad to hear it.  We ran into similar issues in the SDK for data calls coming from the HTTPCurlClient class, but in the most recent release I believe they fixed it.
